### ISSUE TITLE
Plot.Line d3 interpolation not accessible?

### ISSUE THREAD

**Issue by HuysentruytRuben** [palantir/plottable#1774] opened 2015-03-27 11:42 UTC
I've been trying to get d3's interpolate to work on the line in a Plot.Line plot, but have been unsuccessful so far.

I'm talking about this ["Smoothing out the lines in d3.js"](http://www.d3noob.org/2013/01/smoothing-out-lines-in-d3js.html) functionality that is in d3.

```
new Plottable.Plot.Line(someXScale, someYScale)
               .addDataset(someData)
               .project("x", someXAccessorFunction, someXScale)
               .project("y", someYAccessorFunction, someYScale)
               .project("stroke", "#FF0000")
               .interpolate("monotone")); //<--- this would be an ideal usecase
```

I have been trying to modify Plottablejs to try and get the above to work but with no success.
Would be amazing if this could be added or if someone could point out how this is already possible.

**Comment by jtlan** [comment] 2015-04-07 18:12
Closing as duplicate of #757.

**Closed by jtlan** 2015-04-07 18:12 UTC
