### ISSUE TITLE
public-underscore methods in Drawer

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2213] opened 2015-06-03 18:04 UTC
```Typescript
public _getRenderArea();
public _getSelector();
public _getSelection(index: number);
```

Should probably just become public, and the "get" removed.

**Comment by aicioara** [comment] 2015-06-03 20:48
Duplicate of https://github.com/palantir/plottable/issues/2198

**Closed by aicioara** 2015-06-03 20:48 UTC
Labels: API Refactor
