### ISSUE TITLE
Option to restrict to only panning or only zooming in PanZoom interaction

### ISSUE THREAD

**Issue by joyt** [palantir/plottable#3002] opened 2015-11-27 18:04 UTC
For example:
`var pzi = new Plottable.Interactions.PanZoom().enableZoom(false).attachTo(plot);`
Now the user may only drag the chart around, using the mousewheel will not affect the chart.

**Comment by hellochar** [comment] 2017-01-09 21:11
Hey @joyt I'm closing as a dupe of #3092 which has more activity on it, lemme know if they aren't the same ticket!

**Closed by hellochar** 2017-01-09 21:11 UTC
Labels: Type: Feature Request
