### ISSUE TITLE
Invalid value in a pie chart still shows key in legend

### ISSUE THREAD

**Issue by sarapeletz** [palantir/plottable#2602] opened 2015-08-12 18:56 UTC
Repro steps:
1. Add values to a pie chart: [1,2,"e",3]
2. Add keys: ["a","b","c","d"]
3. See that the slice doesn't get drawn for the invalid value, but that the legend still shows the key

See SLATE-2582

**Comment by crmorford** [comment] 2015-08-12 19:01
repro :( http://jsfiddle.net/k5yaLhyp/

**Comment by jtlan** [comment] 2015-08-12 19:07
Arguably this behavior makes sense, since the *key* itself is still valid. Consider a similar case, where the `Scales.Color` is used to set the color of individual `Dataset`s in a `Plots.StackedBar`. Even if all the data points in one of the `Dataset`s are missing/invalid, it should still appear in the ordering, right?

**Comment by jtlan** [comment] 2015-08-12 19:08
Alternatively, `Plots.Pie` could have specialized logic for this, where in reporting the extent of values on the color scale's domain it ignores invalid data points.

**Comment by bluong** [comment] 2015-08-12 20:40
All `Plots` could theoretically do the above you mentioned @jtlan I think.  In all `Plots`, currently, even the invalid values hold some weight in determining the extent of the scale when they arguably shouldn't

**Comment by ztsai** [comment] 2015-08-13 21:42
@jtlan @bluong @crmorford have we concluded what's expected behavior here?

**Comment by ztsai** [comment] 2015-08-19 19:22
talked to slate (Natasha); close this as non issue

**Closed by ztsai** 2015-08-19 19:22 UTC
