### ISSUE TITLE
Unnecessary quadratic slowdown when adding datasets to stacked plot

### ISSUE THREAD

**Issue by jhorowitz-coursera** [palantir/plottable#2418] opened 2015-06-29 23:36 UTC
## Problem

If I have 150 datasets in `myDatasets`, and I call

``` javascript
new Plottable.Plots.StackedArea().datasets(myDatasets);
```

the resulting computation can take over 30 seconds on a powerful machine.
## Cause

The cause of this slow-down is that `.datasets` calls  `.addDataset` for each dataset, and every call to `.addDataset` ends up triggering a call to `Plottable.Utils.Stacking.stack`. Every call to `.stack` recomputes the stacking from scratch. It never takes more than ~0.3sec, but it's being called for every added dataset, so the time adds up.

_Stack trace:_

```
stack @ plottable.js:663
StackedArea._updateStackExtentsAndOffsets @ plottable.js:8124
StackedArea._updateExtentsForProperty @ plottable.js:8103
(anonymous function) @ plottable.js:6127
d3_class.forEach @ d3.js:341
Plot._updateExtents @ plottable.js:6127
Plot._onDatasetUpdate @ plottable.js:6035
Area._onDatasetUpdate @ plottable.js:7851
StackedArea._onDatasetUpdate @ plottable.js:8097
Plot.addDataset @ plottable.js:6015
Area.addDataset @ plottable.js:7860
(anonymous function) @ plottable.js:6228
Plot.datasets @ plottable.js:6228
```
## Proposed solution

The easiest way I can think of to fix this would be to add an additional argument to `.addDataset` called `suppressUpdates` (or something less silly). If provided, it would tell `.addDataset` not to call `._onDatasetUpdate()`. Then `.datasets` could choose to suppress updates and call `._onDatasetUpdate()` itself after all the datasets were added correctly.

Thoughts? I'd be happy to submit a PR myself, or to let someone else take care of this. :stuck_out_tongue:

**Comment by aicioara** [comment] 2015-06-29 23:52
@jhorowitz-coursera just to make sure, you are testing this on latest version (1.1.0). We have major improvements on stacking in this release, which we did not have in version 1.0.0.

I tested the issue myself and it currently takes 5 seconds for 150 datasets of 100 data points each. This is not ideal and definitely will be improved, but it is better than the 30 seconds, until we implement the fix. PRs are always welcome

**Comment by joshuahhh** [comment] 2015-07-01 03:18
@aicioara yup, this is on 1.1.0. I'll send in a rough PR and we can go from there. (Thanks!)

**Comment by aicioara** [comment] 2015-08-18 18:22
150 Datasets
Before: http://jsfiddle.net/cn9x2p5j/1/ - `3000 ms`

**Comment by aicioara** [comment] 2015-08-18 18:52
150 Datasets
After: http://jsfiddle.net/cn9x2p5j/3/ - `36 ms`

**Comment by crmorford** [comment] 2015-08-25 00:23
@aicioara is this ready to close?

**Comment by bluong** [comment] 2015-08-25 00:36
@crmorford Not yet.  The batch setter / getter now nicely will not have the quadratic slowdown, but there is a way for the `add` `remove` functions to also not have this quadratic slowdown

**Comment by jhorowitz-coursera** [comment] 2015-08-25 00:39
Sorry I've been AWOL with this. (I was having trouble with the CLA.) I'm glad you've gotten in a fix! Thanks.

**Comment by aicioara** [comment] 2015-08-25 04:21
Hello @jhorowitz-coursera . An improvement went in version `v1.8.0` (details here)[https://github.com/palantir/plottable/releases/tag/v1.8.0] . Let us know if that works for you. Any feedback is welcome. We are sorry we could not take your pull request, but we hope you find the fix at least satisfactory.

The issue is still open because @bluong identified another area of potential fix. However it has been amended for version `v1.10.0` or later.

**Comment by hellochar** [comment] 2017-02-23 23:21
Closing since original issue was resolved

**Closed by hellochar** 2017-02-23 23:21 UTC
Labels: Domain: Performance
