### ISSUE TITLE
Timeseires y-axis label formatting for large numbers

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2589] opened 2015-08-10 18:53 UTC
y-axis shows labels like "7..." rather than 7,000 or 70,000,000 - so it is hard to interpret. There is a workaround for this by wrapping in a $timeout to delay. Figure out why the timeout fixes this, and if there's actually an issue with the implementation. 

Might be able to be fixed by: https://github.com/palantir/plottable/issues/1353

**Comment by ztsai** [comment] 2015-09-10 00:44
repo: http://jsfiddle.net/ztsai/zg13fjt2/
talked to contour, and it seems like the cause of the bug is not large numbers
due to their implementation, the `axis` is hidden when `redraw()` occurs, and thus `width` assigned to the `axis` is minimal

**Comment by ztsai** [comment] 2015-09-10 00:52
close as not a bug

**Comment by ztsai** [comment] 2015-10-06 22:14
http://jsfiddle.net/ztsai/zg13fjt2/5/
actually, spent more time investigating, `computedWidth` is cached and is not invalidated during `redraw` which sounds like a bug on our end

**Closed** 2015-10-08 21:51 UTC
Labels: bug, Contour
