### ISSUE TITLE
Category axis labels overflow SVG

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#3059] opened 2016-02-25 17:26 UTC
Create a chart with a category axis, and add a data point with a very long category name.

Expected: category text is wrapped and/or truncated such that it doesn't overflow the SVG container
Actual: category text overflows the SVG container

![screen shot 2016-02-25 at 9 22 14 am](https://cloud.githubusercontent.com/assets/11776100/13328072/8fcd9648-dba1-11e5-9a53-ac81b8cc80da.png)

**Comment by hellochar** [comment] 2017-01-13 02:47
This is actually a dupe of #3152 (now that we've added trimming out-of-bounds labels) and will probably be fixed with the new svg-typewriter release; going to close this in favor of that ticket.

**Closed as completed by hellochar** 2017-01-13 02:47 UTC
Labels: Type: Bug, P2
