### ISSUE TITLE
Scatter plot with text labels

### ISSUE THREAD

**Issue by siFeiden** [palantir/plottable#3103] opened 2016-11-02 21:12 UTC
Hi, I'd like to create a scatter plot where each data point either is a text label or is an icon that has a text label right next to it. Find an example [here](http://www.clear-lines.com/blog/image.axd?picture=WindowsLiveWriter/ExcelScatterPlotwithlabelscolorsandmarke/1C1462E0/PowerScatterPlot_thumb.png).

Is this possible?

**Comment by CalvinFernandez** [comment] 2016-11-17 16:28
Hey @siFeiden, unfortunately this isn't possible at the moment -- would you like me to open a feature request for this?

**Comment by siFeiden** [comment] 2016-11-30 12:38
Hi @CalvinFernandez , yes this would be great!

**Comment by hellochar** [comment] 2017-01-16 20:11
Dupe of #2617, lets consolidate conversation over there ( @siFeiden looks like there's discussion of some workarounds in that thread)

**Closed as completed by hellochar** 2017-01-16 20:11 UTC
Labels: Type: Feature Request, P3, External PRs Welcome, Type: Enhancement
