### ISSUE TITLE
Interactions should have destruction call

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1442] opened 2014-12-10 06:36 UTC
Currently, `Interaction`s don't have a destruction call. Since they maintain references to the `Component` they're attached to, and vice versa, the circular reference may interfere with garbage collection. Adding a destructor or some sort of cleanup call allows us to disconnect / destroy the interaction when the Component is `remove()`d.

**Comment by aicioara** [comment] 2015-07-08 00:51
We have `detachFrom` now. Added in https://github.com/palantir/plottable/pull/1997

**Comment by aicioara** [comment] 2015-07-08 00:54
However, it seems like when the component is removed, the interaction is still around. We need a `component.offAnchor` callback for this

**Comment by aicioara** [comment] 2015-07-08 23:19
Duplicate of the better documented https://github.com/palantir/plottable/issues/2334

**Closed by aicioara** 2015-07-08 23:19 UTC
Labels: bug, Feature Request, Interaction, p2
