### ISSUE TITLE
Zoom Out Turns to Black Screen with Gridlines

### ISSUE THREAD

**Issue by caradfb** [palantir/plottable#2687] opened 2015-08-27 17:45 UTC
Repro:
1. Enable Panzoom on chart with gridlines
2. Zoom out and gridlines cover chart
3. Chart turns black

See attached screenshot for example.
<img width="982" alt="screen shot 2015-08-27 at 10 41 49 am" src="https://cloud.githubusercontent.com/assets/11103518/9528296/a6d5b9d4-4ca8-11e5-8b95-fbc2e3be6c56.png">

**Comment by jtlan** [comment] 2015-08-28 00:19
Dug into this offline -- there's a `TickGenerators.Interval` on the `Gridlines` in the chart shown, which means they are working as intended.

Closing as invalid.

**Closed by jtlan** 2015-08-28 00:19 UTC
