### ISSUE TITLE
Values isolated by NaNs on Line/Area aren't drawn

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1142] opened 2014-10-03 01:04 UTC
This data:
```Typescript
var data = [
  { x: 0, y: 0 },
  { x: 1, y: 1 },
  { x: 2, y: NaN },
  { x: 3, y: 3 },
  { x: 4, y: NaN },
  { x: 5, y: 5 },
  { x: 6, y: 6 }
];
```

Gets drawn like this on `Plot.Line` and `Plot.Area`:

![screen shot 2014-10-02 at 6 00 46 pm](https://cloud.githubusercontent.com/assets/1440449/4500726/f6301cee-4a98-11e4-8ce6-943b57c88469.png)

Note that the value `{ x: 3, y: 3 }` isn't drawn because it's been isolated by invalid values. On HH points isolated in this way would be rendered as a single circle, as though they were an isolated scatterplot point. Should we implement similar logic here?

**Comment by aicioara** [comment] 2015-07-07 23:46
Duplicate of https://github.com/palantir/plottable/issues/1866

**Closed by aicioara** 2015-07-07 23:46 UTC
Labels: p2, Visual Design
