### ISSUE TITLE
Vertical Bar Labels not showing on Firefox and iPad

### ISSUE THREAD

**Issue by speletz** [palantir/plottable#2210] opened 2015-06-02 23:52 UTC
Vertical bar labels are not showing on Firefox (37.0.1) and iPad. 

![screen shot 2015-06-02 at 4 50 23 pm](https://cloud.githubusercontent.com/assets/7562851/7949852/82c13fa4-0947-11e5-8689-58cbcfebc526.png)

**Comment by aicioara** [comment] 2015-06-03 23:04
This should probably be solved together with https://github.com/palantir/plottable/issues/2122

**Comment by rcchen** [comment] 2015-06-30 23:03
Vertical bar labels work in Firefox and iOS; the issue is that because of slight differences in how SVG elements are measured, it will work in Chrome and not in Firefox/iOS for this specific case (threshold is 35 or something, Chrome measures at 34.4 and Firefox measures at 35.2).

Looking into using an open source web font (#2422) to at least establish some amount of consistency between OSes.

**Comment by rcchen** [comment] 2015-07-07 16:14
Talked to @sarapeletz and they're in the process of writing new testing tools so this issue hasn't been addressed yet; will leave open until that is complete.

**Comment by aicioara** [comment] 2015-07-07 18:02
@rcchen Will this be solved by https://github.com/palantir/plottable/issues/2422 ?

**Comment by rcchen** [comment] 2015-07-07 18:21
@aicioara no, this issue afaik is invalid because vertical bar labels do show up in both Firefox and mobile Safari, as long as your component is wide enough. Just keeping it open until we get confirmation that the OP has resolved the issue on their end as well.

**Comment by CalvinFernandez** [comment] 2017-01-20 18:55
no action on this ticket. closing

**Closed by CalvinFernandez** 2017-01-20 18:55 UTC
Labels: Slate, Type: Bug
