### ISSUE TITLE
Time axis has misleading tick-label size

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1605] opened 2015-02-10 00:42 UTC
Making a repro would take longer, and we all know what this is referencing, so ASCII art:
[.........Jan...|...Jul...|...Jan...|...Jul........]
Time axes look like this when there isn't room to add another label to the left or right side.
This is misleading, because a data point in January of the next (increasing) year will look like it's actually halfway through the second half of the year.

**Comment by jtlan** [comment] 2015-02-10 01:12
Duplicate of #1606.

**Closed by jtlan** 2015-02-10 01:12 UTC
Labels: bug, p1, slate, Visual Design
