### ISSUE TITLE
Selection-box Component

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1572] opened 2015-02-03 21:44 UTC
![screen shot 2015-02-03 at 1 41 04 pm](https://cloud.githubusercontent.com/assets/1440449/6030164/616edef6-abaa-11e4-8270-fd9d9a3543ca.png)

Create a `Component` that draws selection boxes. This `Component` will replace the box-drawing behavior that is currently tightly coupled with `Interaction.Dragbox`.

It should support these features:
 - Ability to draw multiple boxes
 - Ability to resize boxes (horizontally, vertically, or both)
 - Ability to dismiss boxes (maybe by clicking an X in the corner?)
 - Ability to query bounds of the boxes (either at creation or modification, or on command)

Consult Design on appropriate appearance, behavior, etc.

**Comment by jtlan** [comment] 2015-04-20 18:40
Partially completed by #1816. Still need a mechanism to dismiss the box. Maybe only on `DragBoxLayer`?

**Comment by aicioara** [comment] 2015-07-08 19:09
Looks like a duplicate of https://github.com/palantir/plottable/issues/1533 . Closing this one

**Closed** 2015-07-08 19:10 UTC
Labels: Feature Request, p2, Visual Design
