### ISSUE TITLE
Single Bars on Bar Plot don't render with x value > 1 || value < 0

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2853] opened 2015-10-06 23:55 UTC
Found by a Slate customer.
http://jsfiddle.net/j5b9f60c/26/

Additional notes:
this is ugly even when the bar plot is at x = 0  
![screen shot 2015-10-06 at 4 54 50 pm](https://cloud.githubusercontent.com/assets/7527733/10325981/070fd110-6c4b-11e5-8d23-534d82cded42.png)

http://jsfiddle.net/j5b9f60c/27/

horizontal too: http://jsfiddle.net/j5b9f60c/29/

**Comment by christinaforney** [comment] 2015-10-07 17:59
#2857

**Comment by jtlan** [comment] 2015-10-07 22:50
Duplicate of #https://github.com/palantir/plottable/issues/2788.

**Comment by christinaforney** [comment] 2015-10-19 18:41
Duplicate issue has been closed

**Closed by christinaforney** 2015-10-19 18:41 UTC
Labels: bug, p1, slate
