### ISSUE TITLE
If you zoom insanely far, data disappears

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#574] opened 2014-06-20 00:36 UTC
Repro:
1. go to http://jsfiddle.net/df5a5/2/
2. zoom in hella far on a specific point
3. around  the point where the values on the x-axis are .5 apart, the point disappears

note: if you start with a smaller domain, you can zoom in  to much smaller x-values before having problems. http://jsfiddle.net/df5a5/1/

**Comment by bluong** [comment] 2015-04-29 20:46
Updated jsfiddle: http://jsfiddle.net/df5a5/4/

**Comment by aicioara** [comment] 2015-07-06 21:50
It does not seem to be an issue on the Scatter Plot anymore http://jsfiddle.net/df5a5/11/

**Comment by aicioara** [comment] 2015-07-06 21:55
This only fails on `Scales.Numeric`, which is a duplicate of #2437

**Comment by aicioara** [comment] 2015-07-06 21:59
Unless @crmorford disagrees, closing this as partly fixed, party duplicate of #2437

**Closed by aicioara** 2015-07-06 21:59 UTC
Labels: bug, p2
